export const PERSONA_SUMMARY_FIELDS = [
  "id",
  "name",
  "comment",
  "description",
  "personality",
  "scenario",
  "backstory",
  "appearance",
  "tags",
  "avatarPath",
  "avatarFilePath",
  "avatarFilename",
  "avatarCrop",
  "isActive",
  "active",
  "createdAt",
  "nameColor",
  "dialogueColor",
  "boxColor",
] as const;
