// ──────────────────────────────────────────────
// Combat Encounter Types
// ──────────────────────────────────────────────
// Modeled after RPG Companion's encounter system:
// A separate turn-based combat modal that runs
// alongside the main roleplay, producing a summary
// that gets injected back into the chat.
// ──────────────────────────────────────────────

/** Attack definition for party members and enemies. */
export interface CombatAttack {
  name: string;
  type: "single-target" | "AoE" | "both";
  /** Optional combat tuning generated by the GM. */
  description?: string;
  power?: number;
  cooldown?: number;
  element?: string;
  statusEffect?: string;
}

/** A status effect applied to a combatant. */
export interface CombatStatus {
  name: string;
  emoji: string;
  duration: number;
  modifier?: number;
  stat?: "attack" | "defense" | "speed" | "hp";
}

/** A player inventory item interpreted for this specific encounter. */
export interface CombatItemEffect {
  name: string;
  target: "self" | "ally" | "enemy" | "any";
  type: "heal" | "damage" | "buff" | "debuff" | "status" | "utility";
  description: string;
  power?: number;
  element?: string;
  status?: CombatStatus;
  consumes?: boolean;
}

/** One generated in-combat dialogue cue. */
export interface CombatDialogueCue {
  speaker: string;
  content: string;
  type: "main" | "side" | "extra" | "thought" | "whisper";
  expression?: string;
  target?: string;
  trigger:
    | "intro"
    | "round"
    | "attack"
    | "hit"
    | "charge"
    | "phase_75"
    | "phase_50"
    | "phase_25"
    | "low_hp"
    | "victory"
    | "defeat";
  round?: number;
  everyNRounds?: number;
}

/** Optional boss/special encounter rule generated by the GM. */
export interface CombatMechanic {
  name: string;
  description: string;
  ownerName?: string;
  trigger: "round_interval" | "hp_threshold" | "on_hit" | "on_attack" | "passive";
  interval?: number;
  hpThreshold?: number;
  counterplay?: string;
  effectType?: "damage_all" | "damage_one" | "buff_self" | "debuff_party" | "status_party" | "status_enemy";
  power?: number;
  element?: string;
  status?: CombatStatus;
}

/** Optional image generation request for special encounters. */
export interface CombatVisualRequest {
  isBossFight?: boolean;
  enemyImagePrompts?: Array<{ name: string; prompt: string }>;
  backgroundPrompt?: string;
  illustrationPrompt?: string;
  slug?: string;
}

/** A member of the player's party. */
export interface CombatPartyMember {
  name: string;
  hp: number;
  maxHp: number;
  attacks: CombatAttack[];
  items: string[];
  statuses: CombatStatus[];
  isPlayer: boolean;
}

/** An enemy in the encounter. */
export interface CombatEnemy {
  name: string;
  hp: number;
  maxHp: number;
  attacks: CombatAttack[];
  statuses: CombatStatus[];
  description: string;
  sprite: string;
}

/** AI-chosen visual styling hints for the combat environment. */
export interface CombatStyleNotes {
  environmentType: string;
  atmosphere: string;
  timeOfDay: string;
  weather: string;
}

/** Full combat state returned by the init prompt. */
export interface CombatInitState {
  party: CombatPartyMember[];
  enemies: CombatEnemy[];
  environment: string;
  styleNotes: CombatStyleNotes;
  itemEffects?: CombatItemEffect[];
  dialogueCues?: CombatDialogueCue[];
  mechanics?: CombatMechanic[];
  visuals?: CombatVisualRequest;
}

/** An action taken by an enemy during a turn. */
export interface CombatEnemyAction {
  enemyName: string;
  action: string;
  target: string;
}

/** An action taken by a non-player party member during a turn. */
export interface CombatPartyAction {
  memberName: string;
  action: string;
  target: string;
}

/** Updated player actions (attacks/items may change mid-combat). */
export interface CombatPlayerActions {
  attacks: CombatAttack[];
  items: string[];
}

/** Result returned by the combat action prompt. */
export interface CombatActionResult {
  combatStats: {
    party: CombatPartyMember[];
    enemies: CombatEnemy[];
  };
  playerActions: CombatPlayerActions;
  enemyActions: CombatEnemyAction[];
  partyActions: CombatPartyAction[];
  narrative: string;
  combatEnd?: boolean;
  result?: "victory" | "defeat" | "fled" | "interrupted";
}

/** An entry in the encounter log, tracked per-turn. */
export interface EncounterLogEntry {
  timestamp: number;
  action: string;
  result: string;
}

/** Narrative style preferences for combat and summary text. */
export interface NarrativeStyle {
  tense: "present" | "past";
  person: "first" | "second" | "third";
  narration: "omniscient" | "limited";
  pov: string;
}

/** User-configurable encounter settings. */
export interface EncounterSettings {
  combatNarrative: NarrativeStyle;
  summaryNarrative: NarrativeStyle;
  historyDepth: number;
}

// ──────────────────────────────────────────────
// API Request / Response Types
// ──────────────────────────────────────────────

/** Payload for initializing an encounter. */
export interface EncounterInitRequest {
  chatId: string;
  connectionId: string | null;
  settings: EncounterSettings;
  /** Optional spellbook lorebook ID to inject spell/attack data into combat */
  spellbookId?: string | null;
}

/** Response from encounter initialization. */
export interface EncounterInitResponse {
  combatState: CombatInitState;
}

/** Payload for resolving an encounter action. */
export interface EncounterActionRequest {
  chatId: string;
  connectionId: string | null;
  action: string;
  combatStats: {
    party: CombatPartyMember[];
    enemies: CombatEnemy[];
    environment: string;
  };
  playerActions: CombatPlayerActions | null;
  encounterLog: EncounterLogEntry[];
  settings: EncounterSettings;
  /** Optional spellbook lorebook ID to inject spell/attack data into combat */
  spellbookId?: string | null;
}

/** Response from encounter action resolution. */
export interface EncounterActionResponse {
  result: CombatActionResult;
  /**
   * True when the model output could not be parsed into a usable combat turn.
   * The caller must surface a retryable error and leave combat state unchanged
   * instead of treating `result` as a real turn.
   */
  invalid?: boolean;
}

/** Payload for summarizing an encounter. */
export interface EncounterSummaryRequest {
  chatId: string;
  connectionId: string | null;
  encounterLog: EncounterLogEntry[];
  result: "victory" | "defeat" | "fled" | "interrupted";
  settings: EncounterSettings;
}

/** Response from encounter summarization. */
export interface EncounterSummaryResponse {
  summary: string;
  messageId: string;
}
